[pytest]
testpaths = tests
addopts   = -v --tb=short

markers =
    case1: Diferencas de grafia (tipograficas)
    case2: Sobrenome e Iniciais dos nomes
    case3: Particulas de e uso de ponto nas abreviacoes opcionais
    case4: Iniciais dos nomes agrupadas e sobrenome
    case5: IDs diferentes para o mesmo autor
    exceptions: Testes de fluxo de excecao
